export const squadData = [
  {
    id: '01',
    name: 'Líbero Passador',
    jobTitle: '@diretor_executivo',
    bgGradient: 'primaryDarkness',
    hobbies: ['#cycling', ' #coffee', '#cinephilia'],
    avatarImg: 'libero.jpeg',
    borderColor: 'primaryDarker',
    btnColor: 'primary',
    btnLabel: 'Entrar em contato',
    btnUrl: 'https://wa.me/message/HMRTNVF66NLRO1',
  },
  {
    id: '02',
    name: 'Marlene Passador',
    jobTitle: '@gestor_financeiro',
    bgGradient: 'orangeDarknessPlus',
    hobbies: ['#cycling', ' #coffee', '#cinephilia'],
    avatarImg: 'marlene.jpg',
    btnColor: 'attention',
    borderColor: 'orangeDarker',
    btnLabel: 'Entrar em contato',
  },
  {
    id: '03',
    name: 'Magda Basso',
    jobTitle: '@gerente_administrativo',
    bgGradient: 'blueDarker',
    hobbies: ['#cycling', ' #coffee', '#cinephilia'],
    avatarImg: 'magda.jpeg',
    btnColor: 'react',
    borderColor: 'blueDarker',
    btnLabel: 'Entrar em contato',
  },
  {
    id: '03',
    name: 'Weverton S.',
    jobTitle: '@engenheiro',
    bgGradient: 'greenDarker',
    hobbies: ['#math', ' #something', '#cinephilia'],
    avatarImg: 'weverton.png',
    btnColor: 'green',
    borderColor: 'greenDarker',
    btnLabel: 'Entrar em contato',
  },
];
